import { Racket } from '../../domain/racket/racket'
import { PlayStyle } from '../../domain/user/playStyle'

// sourced from padelful.com reviews, will swap for PadelfulApiAdapter in prod
export const RACKET_CATALOGUE: Racket[] = [
  {
    id: 'adidas-drive-light-2026',
    name: 'Drive Light 2026',
    brand: 'Adidas',
    shape: 'round',
    level: 'beginner',
    style: PlayStyle.CONTROL,
    price: 80,
    priceRange: 'low',
    weight: 355,
    description: 'Lightweight and forgiving. Round shape with neutral balance makes it extremely easy to handle. Best for players building their technique — arm-friendly with predictable ball output.',
    bestFor: 'Complete beginners who want comfort and control above all else.',
    limitations: 'Lacks power for smashes. Players will outgrow it quickly as they improve.'
  },
  {
    id: 'nox-x-hero-white-2026',
    name: 'X-Hero White 2026',
    brand: 'Nox',
    shape: 'round',
    level: 'beginner',
    style: PlayStyle.CONTROL,
    price: 100,
    priceRange: 'low',
    weight: 360,
    description: 'Solid entry point for developing players. Round shape with medium balance gives reliable control on both defense and attack. Durable construction resists off-center impacts.',
    bestFor: 'Beginners who want to progress without punishing technique errors.',
    limitations: 'Power-hungry players will find smashes lack punch.'
  },
  {
    id: 'siux-astra-control-2026',
    name: 'Astra Control 2026',
    brand: 'Siux',
    shape: 'round',
    level: 'beginner',
    style: PlayStyle.CONTROL,
    price: 90,
    priceRange: 'low',
    weight: 358,
    description: 'Control and forgiveness-first racket. Full fiberglass construction absorbs vibration and generates a smooth feel. Perfect for building points patiently from the back of the court.',
    bestFor: 'Players who value placement and consistency over raw finishing power.',
    limitations: 'Lacks brute power for aggressive smashes and fast offensive volleys.'
  },
  {
    id: 'lok-easy-flow-gen-2-2026',
    name: 'Easy Flow Gen 2 2026',
    brand: 'Lok',
    shape: 'round',
    level: 'intermediate',
    style: PlayStyle.BALANCED,
    price: 180,
    priceRange: 'mid',
    weight: 365,
    description: 'Comfortable control racket for improving players. Round shape with medium balance allows fast preparation and quick changes between defense and attack.',
    bestFor: 'Defensive players who value lob consistency, placement and control.',
    limitations: 'Not enough punch for players who rely on power smashes.'
  },
  {
    id: 'head-extreme-team-2026',
    name: 'Extreme Team 2026',
    brand: 'Head',
    shape: 'diamond',
    level: 'intermediate',
    style: PlayStyle.POWER,
    price: 220,
    priceRange: 'mid',
    weight: 370,
    description: 'Accessible power for intermediate players who want to attack. Diamond shape with medium balance delivers explosive smashes. Auxetic 2.0 technology disperses vibrations for comfort.',
    bestFor: 'Intermediate players growing into an aggressive style without sacrificing comfort.',
    limitations: 'Players switching from round shapes may need adjustment time.'
  },
  {
    id: 'adidas-metalbone-ctrl-2026',
    name: 'Metalbone CTRL 2026',
    brand: 'Adidas',
    shape: 'round',
    level: 'advanced',
    style: PlayStyle.CONTROL,
    price: 320,
    priceRange: 'premium',
    weight: 365,
    description: 'Pro-level control racket with a generous sweet spot. Aluminized Carbon 16K faces deliver crisp ball output. Built for players who dictate points with placement and spin.',
    bestFor: 'Advanced players who construct points tactically and dominate with spin at the net.',
    limitations: 'Players seeking maximum raw smash power may find it short vs diamond models.'
  },
  {
    id: 'adidas-arrow-hit-2026',
    name: 'Arrow Hit 2026',
    brand: 'Adidas',
    shape: 'diamond',
    level: 'advanced',
    style: PlayStyle.POWER,
    price: 280,
    priceRange: 'premium',
    weight: 375,
    description: 'Offensive racket built to attack without forgetting control. Diamond shape with soft EVA core gives explosive smashes and spin generation while remaining comfortable.',
    bestFor: 'Offensive players who dominate from the net and finish points with authority.',
    limitations: 'Demanding in fast defensive situations. Not ideal for primarily defensive players.'
  },
  {
    id: 'siux-fenix-elite-6-2026',
    name: 'Fenix Elite 6 2026',
    brand: 'Siux',
    shape: 'diamond',
    level: 'advanced',
    style: PlayStyle.POWER,
    price: 300,
    priceRange: 'premium',
    weight: 372,
    description: 'Aggressive racket for attacking players who still want solid control. 3K carbon faces with medium-hard EVA core reward a decisive offensive style.',
    bestFor: 'Advanced offensive players who want to raise their attacking game.',
    limitations: 'Demanding in quick defensive exchanges. Adaptation needed from round shapes.'
  },
  {
    id: 'lok-carbon-hype-gen-2-2026',
    name: 'Carbon Hype Gen 2 2026',
    brand: 'Lok',
    shape: 'diamond',
    level: 'advanced',
    style: PlayStyle.POWER,
    price: 260,
    priceRange: 'premium',
    weight: 374,
    description: 'Explosive diamond for offensive players who live close to the net. High balance loads mass in the head for devastating smashes and aggressive bandejas.',
    bestFor: 'Left-side or aggressive right-side players who base their game on smashes and net pressure.',
    limitations: 'Demands good mechanics in defense. Not suitable for beginners.'
  },
  {
    id: 'babolat-viper-3-juan-lebron-2026',
    name: 'Viper 3.0 Juan Lebrón 2026',
    brand: 'Babolat',
    shape: 'diamond',
    level: 'advanced',
    style: PlayStyle.POWER,
    price: 390,
    priceRange: 'premium',
    weight: 378,
    description: "Juan Lebrón's signature weapon. 3K carbon faces with Black EVA core deliver brutal power with precise control. Every aspect positioned for attacking dominance.",
    bestFor: 'Elite-level aggressive players who attack from every area of the court.',
    limitations: 'Hard feel and demanding balance — not forgiving for developing technique.'
  }
]